routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Customer\PesananController;
use App\Http\Controllers\Pengelola\PesananController as PengelolaPesananController;
use App\Http\Controllers\Pengelola\KatalogController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('guest.main');
})->name('guest.main');

require __DIR__ . '/auth.php';

// Route customer
Route::middleware(['auth', 'customer'])
    ->name('customer.')
    ->group(function () {
        Route::get('/pesanan', [PesananController::class, 'viewPesanan'])
            ->name('pesanan');
    });

// Route non customer (pengelola)
Route::middleware(['auth', 'pengelola'])
    ->name('pengelola.')
    ->prefix('pengelola')
    ->group(function () {
        Route::get('/dashboard', function () {
            $active = 'dashboard';
            return view('pengelola.dashboard', [
                'active' => $active,
            ]);
        })->name('dashboard');

        Route::get('pesanan', [PengelolaPesananController::class, 'index'])
            ->name('pesanan');

        Route::resource('katalog', KatalogController::class);
    });

resources/views/guest/_partials/content.blade.php
<div class="row push">
    <div id="page-loader" style="opacity: .5" class="show"></div>
    <div class="col-xl-4 order-xl-1">
        <!-- Shopping Cart -->
        @livewire('cart')
        <!-- END Shopping Cart -->
    </div>
    <div class="col-xl-8 order-xl-0">
        @livewire('product');
    </div>
    @livewire('checkout')
</div>

resources/views/guest/_partials/header.blade.php
<header id="page-header" style="padding-left: 0">
    <!-- Header Content -->
    <div class="content-header">
        <!-- Left Section -->
        <div class="d-flex align-items-center">
            <!-- Toggle Sidebar -->
            <!-- Layout API, functionality initialized in Template._uiApiLayout()-->
            {{-- <button type="button" class="btn btn-sm btn-dual mr-2" data-toggle="layout" data-action="sidebar_toggle">
                <i class="fa fa-fw fa-bars"></i>
            </button> --}}
            <a href="{{ route('guest.main') }}">
                <img src="{{ asset('assets/img/jenggala_v1.jpg') }}" alt="Jenggala"
                    style="width: 55px"
                >
            </a>
            <!-- END Toggle Sidebar -->
        </div>
        <!-- END Left Section -->

        <!-- Right Section -->
        <div class="d-flex align-items-center">
            <!-- User Dropdown -->
            @auth
                <div class="dropdown d-inline-block ml-2">
                    <button type="button" class="btn btn-sm btn-dual d-flex align-items-center" id="page-header-user-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <img class="rounded-circle" 
                            alt="Header Avatar" 
                            style="width: 21px;"
                            @if(auth()->user()->role == 'Konsumen')
                                src="{{ auth()->user()->avatar }}"
                            @else
                                src="{{ asset('assets/oneui/media/avatars/avatar10.jpg') }}"
                            @endif
                        >
                        <span class="d-none d-sm-inline-block ml-2">
                            {{ auth()->user()->nama }}
                        </span>
                        <i class="fa fa-fw fa-angle-down d-none d-sm-inline-block ml-1 mt-1"></i>
                    </button>
                    <div class="dropdown-menu dropdown-menu-md dropdown-menu-right p-0 border-0" aria-labelledby="page-header-user-dropdown">
                        <div class="p-3 text-center bg-primary-dark rounded-top">
                            <img class="img-avatar img-avatar48 img-avatar-thumb" alt=""
                            @if(auth()->user()->role == 'Konsumen')
                                src="{{ auth()->user()->avatar }}"
                            @else
                                src="{{ asset('assets/oneui/media/avatars/avatar10.jpg') }}"
                            @endif
                        >
                            <p class="mt-2 mb-0 text-white font-w500">
                                {{ auth()->user()->nama }}
                            </p>
                            <p class="mb-0 text-white-50 font-size-sm">
                                {{ auth()->user()->email }}
                            </p>
                        </div>
                        <div class="p-2">
                            @if(auth()->user()->role == 'Konsumen')
                                <a class="dropdown-item d-flex align-items-center justify-content-between" href="{{ route('customer.pesanan') }}">
                                    <span class="font-size-sm font-w500">Transaksi</span>
                                    <span class="badge badge-pill badge-primary ml-2">
                                        {{ count(auth()->user()->pesanan) }}
                                    </span>
                                </a>
                            @else
                                <a class="dropdown-item d-flex align-items-center justify-content-between" 
                                    href="{{ route('pengelola.dashboard') }}">
                                    <span class="font-size-sm font-w500">
                                        Dashboard
                                    </span>
                                </a>
                            @endif
                            <a class="dropdown-item d-flex align-items-center justify-content-between"
                                href="{{ route('logout') }}"
                                onclick="event.preventDefault();
                                    document.getElementById('form-logout').submit();"
                            >
                                <span class="font-size-sm font-w500">Log Out</span>
                            </a>
                            <form method="POST" action="{{ route('logout') }}" id="form-logout">
                                @csrf
                            </form>
                        </div>
                    </div>
                </div>
            @endauth
            @guest
                <a href="{{ route('login-google') }}"
                    class="btn btn-outline-secondary mr-1">
                    <i class="fa fa-sign-in-alt text-default mr-1"></i>Sign in
                </a>
            @endguest
            <!-- END User Dropdown -->
        </div>
        <!-- END Right Section -->
    </div>
    <!-- END Header Content -->
</header>

resources/views/guest/_partials/hero.blade.php
<div class="bg-image" style="background-image: url({{ asset('assets/oneui/media/photos/photo3@2x.jpg') }});">
    <div class="bg-primary-dark-op">
        <div class="content content-full text-center py-6">
            <h1 class="h2 text-white mb-2">Welcome to our Digital Store!</h1>
            <h2 class="h4 font-w400 text-white-75 mb-0">Feel free to explore over 50.000 products.</h2>
        </div>
    </div>
</div>

resources/views/guest/_partials/pesanan.blade.php
<div class="row justify-content-center">
    <div class="col-md-8">
        <form action="be_pages_ecom_store_checkout.html" method="POST" onsubmit="return false;">
            <!-- Shopping Cart -->
            <div class="block block-rounded">
                <div class="block-header block-header-default">
                    <h3 class="block-title">Pesanan</h3>
                </div>
                <div class="block-content block-content-full">
                    @if(count($pesanan) !== 0)
                        @php
                            $index = 1;
                        @endphp
                        @foreach ($pesanan as $pesanan)
                            <div class="block block-rounded block-themed" id="pesanan{{ $pesanan->id }}">
                                <div class="block-header bg-info">
                                    <h3 class="block-title">Pesanan {{ $index }}</h3>
                                    <div class="block-options">
                                        <button type="button" class="btn-block-option" data-toggle="block-option" data-action="fullscreen_toggle">
                                            <i class="si si-size-fullscreen"></i>
                                        </button>

                                        <button type="button" class="btn-block-option" 
                                        data-toggle="block-option" 
                                        data-action="content_toggle"
                                        {{-- onload="@if(!$loop->first)
                                                One.block('content_hide', '#pesanan{{ $pesanan->id }}');
                                            @endif" --}}
                                        >
                                            <i class="si si-arrow-up"></i>
                                        </button>
                                    </div>
                                </div>
                                <div class="block-content">
                                    <div class="table-responsive" id="table-pesanan">
                                        <table class="table table-borderless table-hover table-vcenter">
                                            <tbody>
                                                <tr>
                                                    <td class="text-center">
                                                        <span class="text-muted h5">Gambar</span>
                                                    </td>
                                                    <td class="text-center">
                                                        <span class="text-muted h5">Nama</span>
                                                    </td>
                                                    <td class="text-center">
                                                        <span class="text-muted h5">
                                                            Status
                                                        </span>
                                                    </td>
                                                    <td class="text-center">
                                                        <span class="text-muted h5">Harga</span>
                                                    </td>
                                                    <td class="text-center">
                                                        <span class="text-muted h5">Qty</span>
                                                    </td>
                                                    <td class="text-center">
                                                        <span class="text-muted h5">
                                                            Jumlah Harga
                                                        </span>
                                                    </td>
                                                </tr>
                                                @foreach ($pesanan->katalog as $katalog)
                                                    <tr>
                                                        <td style="width: 60px;">
                                                            <img class="img-fluid" src="{{ !$katalog->gambar ? asset('assets/img/default_katalog.png') : '' }}" alt="">
                                                        </td>
                                                        <td class="text-center">
                                                            <span class="text-muted h5">
                                                                {{ $katalog->nama }}
                                                            </span>
                                                        </td>
                                                        <td class="text-center">
                                                            @if (
                                                                $katalog->pivot->status_pesanan->status == 'Pesanan Tertunda'
                                                            )
                                                                <span class="badge badge-info">
                                                                    {{ 
                                                                        $katalog->pivot->status_pesanan->status 
                                                                    }}
                                                                </span>
                                                            @elseif (
                                                                $katalog->pivot->status_pesanan->status == 'Pesanan Sedang Proses'
                                                            )
                                                                <span class="badge badge-warning">
                                                                    {{ 
                                                                        $katalog->pivot->status_pesanan->status 
                                                                    }}
                                                                </span>
                                                            @elseif (
                                                                $katalog->pivot->status_pesanan->status == 'Pesanan Selesai'
                                                            )
                                                                <span class="badge badge-success">
                                                                    {{ 
                                                                        $katalog->pivot->status_pesanan->status 
                                                                    }}
                                                                </span>
                                                            @endif
                                                        </td>
                                                        <td class="text-center">
                                                            <div class="font-w600 text-success">
                                                                {{ $katalog->harga }}
                                                            </div>
                                                        </td>
                                                        <td class="text-center">
                                                            <span class="text-muted h5">
                                                                {{ $katalog->pivot->qty }}
                                                            </span>
                                                        </td>
                                                        <td class="text-center">
                                                            <span class="text-muted h5">
                                                                {{ $katalog->jumlah_harga() }}
                                                            </span>
                                                        </td>
                                                    </tr>
                                                @endforeach
                                                <tr class="bg-success-light">
                                                    <td class="text-center" colspan="4">
                                                        <span class="h5 font-w600">
                                                            Total Harga Pesanan
                                                        </span>
                                                    </td>
                                                    <td class="text-center" colspan="3">
                                                        <span class="h5 font-w600 text-success">
                                                            {{ $pesanan->katalog->sum('jumlahHarga') }}
                                                        </span>
                                                    </td>
                                                </tr>
                                                <tr class="bg-success-light">
                                                    <td class="text-center" colspan="4">
                                                        <span class="h5 font-w600">
                                                            Voucher Diskon
                                                        </span>
                                                    </td>
                                                    <td class="text-center" colspan="3">
                                                        <span class="h5 font-w600 text-success">
                                                            {{ $pesanan->tagihan->diskon->diskon }}
                                                        </span>
                                                    </td>
                                                </tr>
                                                <tr class="bg-success-light">
                                                    <td class="text-center" colspan="4">
                                                        <span class="h5 font-w600">
                                                            Dibayar
                                                        </span>
                                                    </td>
                                                    <td class="text-center" colspan="3">
                                                        <span class="h5 font-w600 text-success">
                                                            {{ $pesanan->tagihan->total_harga }}
                                                        </span>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                            @php
                                $index++
                            @endphp
                        @endforeach
                    @else
                        <h4 class="text-center">
                            <i>Tidak ada pesanan</i>
                        </h4>
                    @endif
                </div>
            </div>
            <!-- END Shopping Cart -->
        </form>
    </div>
</div>

resources/views/guest/_partials/sidebar.blade.php
<nav id="sidebar" aria-label="Main Navigation">
    <!-- Side Header -->
    <div class="content-header bg-white-5">
        <!-- Logo -->
        <a class="font-w600 text-dual" href="index.html">
            <span class="smini-visible">
                <i class="fa fa-circle-notch text-primary"></i>
            </span>
            <span class="smini-hide font-size-h5 tracking-wider">
                Jenggala<span class="font-w400">Kops</span>
            </span>
        </a>
        <!-- END Logo -->

        <!-- Extra -->
        <div>
            <!-- Options -->
            <div class="dropdown d-inline-block ml-2">
                <a class="btn btn-sm btn-dual" id="sidebar-themes-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="#">
                    <i class="si si-drop"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right font-size-sm smini-hide border-0" aria-labelledby="sidebar-themes-dropdown">
                    <!-- Color Themes -->
                    <!-- Layout API, functionality initialized in Template._uiHandleTheme() -->
                    <a class="dropdown-item d-flex align-items-center justify-content-between font-w500" data-toggle="theme" data-theme="default" href="#">
                        <span>Default</span>
                        <i class="fa fa-circle text-default"></i>
                    </a>
                    <a class="dropdown-item d-flex align-items-center justify-content-between font-w500" data-toggle="theme" data-theme="assets/css/themes/amethyst.min.css" href="#">
                        <span>Amethyst</span>
                        <i class="fa fa-circle text-amethyst"></i>
                    </a>
                    <a class="dropdown-item d-flex align-items-center justify-content-between font-w500" data-toggle="theme" data-theme="assets/css/themes/city.min.css" href="#">
                        <span>City</span>
                        <i class="fa fa-circle text-city"></i>
                    </a>
                    <a class="dropdown-item d-flex align-items-center justify-content-between font-w500" data-toggle="theme" data-theme="assets/css/themes/flat.min.css" href="#">
                        <span>Flat</span>
                        <i class="fa fa-circle text-flat"></i>
                    </a>
                    <a class="dropdown-item d-flex align-items-center justify-content-between font-w500" data-toggle="theme" data-theme="assets/css/themes/modern.min.css" href="#">
                        <span>Modern</span>
                        <i class="fa fa-circle text-modern"></i>
                    </a>
                    <a class="dropdown-item d-flex align-items-center justify-content-between font-w500" data-toggle="theme" data-theme="assets/css/themes/smooth.min.css" href="#">
                        <span>Smooth</span>
                        <i class="fa fa-circle text-smooth"></i>
                    </a>
                    <!-- END Color Themes -->

                    <div class="dropdown-divider"></div>

                    <!-- Sidebar Styles -->
                    <!-- Layout API, functionality initialized in Template._uiApiLayout() -->
                    <a class="dropdown-item font-w500" data-toggle="layout" data-action="sidebar_style_light" href="#">
                        <span>Sidebar Light</span>
                    </a>
                    <a class="dropdown-item font-w500" data-toggle="layout" data-action="sidebar_style_dark" href="#">
                        <span>Sidebar Dark</span>
                    </a>
                    <!-- Sidebar Styles -->

                    <div class="dropdown-divider"></div>

                    <!-- Header Styles -->
                    <!-- Layout API, functionality initialized in Template._uiApiLayout() -->
                    <a class="dropdown-item font-w500" data-toggle="layout" data-action="header_style_light" href="#">
                        <span>Header Light</span>
                    </a>
                    <a class="dropdown-item font-w500" data-toggle="layout" data-action="header_style_dark" href="#">
                        <span>Header Dark</span>
                    </a>
                    <!-- Header Styles -->
                </div>
            </div>
            <!-- END Options -->

            <!-- Close Sidebar, Visible only on mobile screens -->
            <!-- Layout API, functionality initialized in Template._uiApiLayout() -->
            <a class="d-lg-none btn btn-sm btn-dual ml-1" data-toggle="layout" data-action="sidebar_close" href="javascript:void(0)">
                <i class="fa fa-fw fa-times"></i>
            </a>
            <!-- END Close Sidebar -->
        </div>
        <!-- END Extra -->
    </div>
    <!-- END Side Header -->

    <!-- Sidebar Scrolling -->
    <div class="js-sidebar-scroll">
        <!-- Side Navigation -->
        <div class="content-side">
            <ul class="nav-main">
                <li class="nav-main-item">
                    <a class="nav-main-link" href="be_pages_dashboard.html">
                        {{-- <i class="nav-main-link-icon si si-bag"></i> --}}
                        <span class="nav-main-link-name">Makanan</span>
                    </a>
                </li>
                <li class="nav-main-item">
                    <a class="nav-main-link" href="be_pages_dashboard.html">
                        {{-- <i class="nav-main-link-icon si si-bag"></i> --}}
                        <span class="nav-main-link-name">Minuman</span>
                    </a>
                </li>
            </ul>
        </div>
        <!-- END Side Navigation -->
    </div>
    <!-- END Sidebar Scrolling -->
</nav>