routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Customer\PesananController;
use App\Http\Controllers\Pengelola\PesananController as PengelolaPesananController;
use App\Http\Controllers\Pengelola\KatalogController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('guest.main');
})->name('guest.main');

require __DIR__ . '/auth.php';

// Route customer
Route::middleware(['auth', 'customer'])
    ->name('customer.')
    ->group(function () {
        Route::get('/pesanan', [PesananController::class, 'viewPesanan'])
            ->name('pesanan');
    });

// Route non customer (pengelola)
Route::middleware(['auth', 'pengelola'])
    ->name('pengelola.')
    ->prefix('pengelola')
    ->group(function () {
        Route::get('/dashboard', function () {
            $active = 'dashboard';
            return view('pengelola.dashboard', [
                'active' => $active,
            ]);
        })->name('dashboard');

        Route::get('pesanan', [PengelolaPesananController::class, 'index'])
            ->name('pesanan');

        Route::resource('katalog', KatalogController::class);
    });

app/Http/Livewire/Barista/Dashboard.php
<?php

namespace App\Http\Livewire\Barista;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Builder;
use Livewire\Component;

use App\Models\Tagihan;
use App\Models\Pesanan;

class Dashboard extends Component
{
    /**
     * 1.   a href pending orders mengarah ke sidebar menu orders yang isinya semua pesanan
     * 2.   a href nama pada latest transaction mengarah ke order (per orangan berdasarkan tagihan)
     *      Jadi sekali klik 1 nama maka akan muncul banyak pesanan sesuai id tagihan yg di klik
     * 2.1  Menu transaksi ada filter berdasarkan nama, tanggal, bulan orderBy terbaru paginate 10
     */

    public function render()
    {
        $latestOrder = Tagihan::latest()->limit(10)->get();
        $ordersToday = count(Pesanan::whereDate('created_at', Carbon::today())->get());
        $earningToday = Tagihan::whereDate('created_at', Carbon::today())->get()->sum('total_harga');
        $pendingOrders = Pesanan::whereHas('katalog', function (Builder $query) {
            $query->where('status_pesanan_id', 1)
                ->orWhere('status_pesanan_id', 2);
        })->get();

        return view('livewire.barista.dashboard', [
            'latestOrder' => $latestOrder,
            'ordersToday' => $ordersToday,
            'earningToday' => $earningToday,
            'pendingOrders' => count($pendingOrders),
        ]);
    }
}

app/Http/Livewire/Barista/Pesanan.php
<?php

namespace App\Http\Livewire\Barista;

use Livewire\Component;
use Livewire\WithPagination;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Support\Facades\Gate;

use App\Models\KatalogPesanan;

class Pesanan extends Component
{
    use AuthorizesRequests;
    use WithPagination;
    protected $paginationTheme = 'bootstrap';

    public $search = '';
    public $filterStatus = null;

    public function updatingSearch()
    {
        $this->resetPage();
    }

    public function searching()
    {
        if ($this->search == '') {
            $pesanan = KatalogPesanan::orderBy('created_at', 'desc')->paginate(10);
        } else {
            $pesanan = KatalogPesanan::whereHas('pesanan', function (Builder $query) {
                $query->where('nama', 'like', '%' . $this->search . '%')
                    ->orWhere('no_meja', 'like', '%' . $this->search . '%');
            })
                ->orWhereHas('katalog', function (Builder $query) {
                    $query->where('nama', 'like', '%' . $this->search . '%');
                })
                ->orWhereHas('status_pesanan', function (Builder $query) {
                    $query->where('status', 'like', '%' . $this->search . '%');
                })
                ->orWhere('qty', 'like', '%' . $this->search . '%')
                ->orderBy('created_at', 'desc')
                ->paginate(10);
        }
        return $pesanan;
    }

    public function render()
    {
        $pesananTertunda = KatalogPesanan::where('status_pesanan_id', 1)->count();
        $pesananProses = KatalogPesanan::where('status_pesanan_id', 2)->count();
        $pesananBerhasil = KatalogPesanan::where('status_pesanan_id', 3)->count();
        $seluruhPesanan = KatalogPesanan::all()->count();
        $pesanan = $this->searching();

        return view('livewire.barista.pesanan', [
            'pesanan' => $pesanan,
            'pesananTertunda' => $pesananTertunda,
            'pesananProses' => $pesananProses,
            'pesananBerhasil' => $pesananBerhasil,
            'seluruhPesanan' => $seluruhPesanan,
        ]);
    }

    public function dispatchEvent($event, $type, $pesan, $icon)
    {
        $this->dispatchBrowserEvent($event, [
            'type' => $type,
            'message' => $pesan,
            'icon' => $icon,
        ]);
    }

    public function setPesananProses(KatalogPesanan $data)
    {
        $cekOtorisasi = Gate::inspect('updatePesananProses', $data);
        if (!$cekOtorisasi->allowed()) {
            $this->dispatchEvent(
                'alert',
                'warning',
                $cekOtorisasi->message(),
                'fa fa-exclamation mr-1'
            );
            return;
        }

        $data->status_pesanan_id = 2;
        $data->save(); // simpan
        $this->dispatchEvent(
            'alert',
            'info',
            'Semangat yaa bikininnya',
            // 'Pesanan Siap Diproses',
            'fa fa-info-circle mr-1'
        );
    }

    public function setPesananBerhasil(KatalogPesanan $data)
    {
        $cekOtorisasi = Gate::inspect('updatePesananSelesai', $data);
        if (!$cekOtorisasi->allowed()) {
            $this->dispatchEvent(
                'alert',
                'warning',
                $cekOtorisasi->message(),
                'fa fa-exclamation mr-1'
            );
            return;
        }

        $data->status_pesanan_id = 3; // ubah menjadi selesai
        $data->save(); // simpan
        $this->dispatchEvent(
            'alert',
            'success',
            // 'Pesanan Telah Selesai Diproses',
            'Udah jadi yaa',
            'fa fa-check mr-1'
        );
    }
}

app/Http/Livewire/Cart.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Cart extends Component
{
    public $productAtCart, $totalHarga;
    protected $listeners = ['productAddedToCart' => 'added'];

    public function mount()
    {
        if (session()->has('productInCart')) {
            $this->productAtCart = session('productInCart');
            $this->totalHarga = $this->priceCalculate();
        } else {
            $this->productAtCart = [];
            $this->totalHarga = 0;
        }
    }

    public function priceCalculate()
    {
        $hargaPerItem = null;
        $hargaTotal = 0;

        foreach ($this->productAtCart as $key => $value) {
            $hargaPerItem = $value['model']['harga'] * $value['qty'];
            $hargaTotal += $hargaPerItem;
        }

        return $hargaTotal;
    }

    public function render()
    {
        return view('livewire.cart');
    }

    public function added($product)
    {
        $this->productAtCart = $product;
        $this->totalHarga = $this->priceCalculate();
    }

    public function deleteCheckout($id)
    {
        unset($this->productAtCart[$id]);
        $this->emit('deleteCheckout', $this->productAtCart);
        session(['productInCart' => $this->productAtCart]);
        $this->totalHarga = $this->priceCalculate();
    }

    public function deleteAllCheckout()
    {
        $this->productAtCart = [];
        $this->totalHarga = 0;
        $this->emit('deleteAllCheckout');
        session()->forget('productInCart');
    }
}

app/Http/Livewire/Checkout.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Support\Facades\Gate;
use Illuminate\Validation\Validator;

use App\Models\VoucherDiskon;
use App\Models\Pesanan;
use App\Models\Tagihan;
use App\Models\Katalog;
use App\Models\MetodePembayaran;

class Checkout extends Component
{
    use AuthorizesRequests;

    public $showModalBox;
    public $cart, $totalHarga, $hargaFix;
    public $nama, $no_meja, $nama_pembayar,
        $metode_pembayaran, $metode_pembayaran_selected, $keterangan;
    public $isUseVoucher, $voucherDiskon, $isCanUseVoucher, $isVoucherAvailable,
        $totalHargaAfterDiskon, $hargaDiskon, $voucherDiskonSelected;

    protected $listeners = ['showModalBox' => 'showModalBox'];
    protected $rules = [
        'cart' => 'required|array',
        'cart.*.qty' => 'lte:cart.*.model.stok',
        'nama' => ['required', 'regex:/^[a-zA-Z\s]*$/'],
        'no_meja' => 'required|integer',
        'hargaDiskon' => 'nullable|lte:totalHarga',
        'hargaFix' => 'required',
        'voucherDiskonSelected' => 'nullable|exists:App\Models\VoucherDiskon,id',
        'isCanUseVoucher' => 'exclude_if:voucherDiskonSelected,null|accepted',
        'isVoucherAvailable' => 'exclude_if:voucherDiskonSelected,null|accepted',
        'nama_pembayar' => ['required', 'regex:/^[a-zA-Z\s]*$/'],
        'metode_pembayaran_selected' => 'required|exists:App\Models\MetodePembayaran,id',
        'keterangan' => 'nullable'
    ];

    protected $messages = [
        'cart.*.qty.lte' => 'Stok :attribute tidak mencukupi',
        'voucherDiskonSelected.exists' => 'Hanya bisa menggunakan voucher yang tersedia pada database',
        'nama.required' => 'Nama harus diisi',
        'nama.regex' => 'Nama hanya boleh mengandung huruf',
        'no_meja.required' => 'Nomor meja harus diisi',
        'no_meja.integer' => 'Nomor meja hanya mengandung angka',
        'hargaDiskon.lte' => 'Harga diskon tidak boleh melebihi total harga',
        'isCanUseVoucher.accepted' => 'Harga diskon hanya bisa digunakan sesuai minimal pembelian',
        'isVoucherAvailable.accepted' => 'Stok untuk voucher ini telah habis',
        'nama_pembayar.required' => 'Nama pembayar harus diisi',
        'nama_pembayar.regex' => 'Nama pembayar hanya boleh mengandung huruf',
        'metode_pembayaran_selected.required' => 'Metode pembayaran harus diisi',
    ];

    public function mount()
    {
        $this->cart = [];
        $this->totalHarga = null;
        $this->voucherDiskon = VoucherDiskon::whereNotIn('stok', [0])->get();
        $this->isUseVoucher = false;
        $this->isCanUseVoucher = false;
        $this->isVoucherAvailable = false;
        $this->metode_pembayaran = MetodePembayaran::all();
        $this->nama = null;
        $this->no_meja = null;
        $this->nama_pembayar = null;
        $this->keterangan = null;
        $this->metode_pembayaran_selected = null;
        $this->voucherDiskonSelected = null;
        $this->showModalBox = false;
    }

    public function showModalBox($data)
    {
        $cart = [];
        foreach ($data[0] as $dt) {
            $cart[$dt['model']['nama']] = $dt;
        }
        $this->cart = $cart;
        $this->totalHarga = $data[1];

        if ($this->isUseVoucher) {
            $this->hargaFix = $this->totalHargaAfterDiskon;
        } else {
            $this->hargaFix = $this->totalHarga;
        }

        $this->openModalBox();
    }

    public function openModalBox()
    {
        $this->showModalBox = true;
    }

    public function closeModalBox()
    {
        $this->showModalBox = false;
        $this->reset([
            'nama', 'no_meja', 'voucherDiskonSelected', 'nama_pembayar',
            'metode_pembayaran_selected', 'keterangan', 'isUseVoucher',
            'isVoucherAvailable'
        ]);

        $this->resetErrorBag();
        $this->resetValidation();
    }

    public function render()
    {
        return view('livewire.checkout');
    }

    public function pesan()
    {
        $otorisasi = Gate::inspect('create', Pesanan::class);

        if (!$otorisasi->allowed() && $otorisasi->code() == 403) {
            return abort($otorisasi->code(), $otorisasi->message());
        }

        if (!$otorisasi->allowed() && $otorisasi->code() == 401) {
            return redirect()->route('login-google');
        }

        $this->withValidator(function (Validator $validator) {
            $validator->setImplicitAttributesFormatter(function ($a) {
                return explode('.', $a)[1];
            });
        })->validate();

        // create data di table pesanan (nama, no meja)
        $pesanan = Pesanan::create([
            'nama' => $this->nama,
            'no_meja' => $this->no_meja,
            'user_id' => auth()->user()->id,
        ]);

        if ($pesanan) {
            // create data di table katalog_pesanan (katalog_id, pesanan_id, qty)
            foreach ($this->cart as $katalog) {
                $pesanan->katalog()->attach($katalog['model']['id'], [
                    'qty' => $katalog['qty'],
                ]);

                // Kurangi stok
                $katalogModel = Katalog::find($katalog['model']['id']);
                $katalogModel->stok -= $katalog['qty'];
                $katalogModel->save();
            }

            // create data di table tagihan 
            $tagihan = new Tagihan([
                'total_harga' => $this->hargaFix,
                'voucher_diskon_id' => $this->voucherDiskonSelected,
                'nama_pembayar' => $this->nama_pembayar,
                'metode_pembayaran_id' => $this->metode_pembayaran_selected,
                'keterangan'    => $this->keterangan ?? null,
                'status_pembayaran_id' => 2,
            ]);

            $pesanan->tagihan()->save($tagihan);

            // jika menggunakan diskon, kurangi stoknya karena sudah dipakai
            if ($this->voucherDiskonSelected) {
                $voucherDiskon = VoucherDiskon::firstWhere('id', $this->voucherDiskonSelected);
                $voucherDiskon->stok -= 1;
                $voucherDiskon->save();
            }

            // delete session('addProductCart')
            session()->forget('productInCart');

            // set flash message
            session()->flash('pesananAdded', 'Pemesanan Berhasil.');

            return redirect()->route('guest.main');
        }
    }

    public function updateTotalHarga($model)
    {
        $model = VoucherDiskon::where('id', $model)->firstOr(function () {
            return null;
        });

        if ($model) {

            if ($this->totalHarga >= $model->minimal_pembelian_total_harga) {
                $this->isCanUseVoucher = true;
            } else {
                $this->isCanUseVoucher = false;
            }

            if ($model->stok == 0) {
                $this->isVoucherAvailable = false;
            } else {
                $this->isVoucherAvailable = true;
            }

            $this->isUseVoucher = true;
            $this->hargaDiskon = $model->diskon;
            $this->voucherDiskonSelected = $model->id;
            $this->totalHargaAfterDiskon = $this->totalHarga - $this->hargaDiskon;
            $this->hargaFix = $this->totalHargaAfterDiskon;
        } else {
            $this->isUseVoucher = false;
            $this->isCanUseVoucher = false;
            $this->isVoucherAvailable = false;
            $this->hargaFix = $this->totalHarga;
            $this->voucherDiskonSelected = null;
        }
    }
}

app/Http/Livewire/Kategori.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

use App\Models\Kategori as KategoriModel;

class Kategori extends Component
{
    public $kategoriAll;

    public function mount()
    {
        $this->kategoriAll = KategoriModel::all();
    }

    public function render()
    {
        return view('livewire.kategori');
    }
}

resources/views/livewire/barista/dashboard.blade.php
<div wire:poll>
    <!-- Quick Overview -->
    <div class="row">
        <div class="col-6 col-lg-4">
            <a class="block block-rounded block-link-shadow text-center" 
                href="{{ route('pengelola.pesanan') }}">
                <div class="block-content block-content-full">
                    <div class="font-size-h2 text-primary">{{ $pendingOrders }}</div>
                </div>
                <div class="block-content py-2 bg-body-light">
                    <p class="font-w600 font-size-sm text-muted mb-0">
                        Transaksi Tertunda
                    </p>
                </div>
            </a>
        </div>
        <div class="col-6 col-lg-4">
            <div class="block block-rounded block-link-shadow text-center">
                <div class="block-content block-content-full">
                    <div class="font-size-h2 text-dark">{{ $ordersToday }}</div>
                </div>
                <div class="block-content py-2 bg-body-light">
                    <p class="font-w600 font-size-sm text-muted mb-0">
                        Transaksi Hari Ini
                    </p>
                </div>
            </div>
        </div>
        <div class="col-6 col-lg-4">
            <div class="block block-rounded block-link-shadow text-center">
                <div class="block-content block-content-full">
                    <div class="font-size-h2 text-dark">Rp. {{ $earningToday }}</div>
                </div>
                <div class="block-content py-2 bg-body-light">
                    <p class="font-w600 font-size-sm text-muted mb-0">
                        Pendapatan Hari Ini
                    </p>
                </div>
            </div>
        </div>
    </div>
    <!-- END Quick Overview -->

    <!-- Top Products and Latest Orders -->
    <div class="row">
        <div class="col-12">
            <!-- Latest Orders -->
            <div class="block block-rounded">
                <div class="block-header block-header-default">
                    <h3 class="block-title">Transaksi Terbaru</h3>
                </div>
                <div class="block-content">
                    <div class="table-responsive">
                        <table class="table table-borderless table-striped table-vcenter font-size-sm">
                            <tbody>
                                @forelse ($latestOrder as $order)
                                    <tr>
                                        <td class="font-w600 text-center" style="width: 100px;">
                                            <a href="#">{{ $order->id }}</a>
                                        </td>
                                        <td class="font-w600 text-center">
                                            <a href="#">
                                                {{ $order->pesanan->nama }}
                                            </a>
                                        </td>
                                        <td class="font-w600 text-center">
                                            <a href="#">
                                                {{ $order->created_at }}
                                            </a>
                                        </td>
                                        <td class="font-w600 text-right">
                                            Rp.{{ $order->total_harga }}
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="4">Tidak ada pesanan</td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- END Latest Orders -->
        </div>
    </div>
    <!-- END Top Products and Latest Orders -->
</div>

resources/views/livewire/barista/pesanan.blade.php
<div wire:poll>
    <!-- Quick Overview -->
    <div class="row">
        <div class="col-6 col-lg-4">
            <div class="block block-rounded block-link-shadow text-center">
                <div class="block-content block-content-full">
                    <div class="font-size-h2 text-primary">
                        {{ $pesananTertunda }}
                    </div>
                </div>
                <div class="block-content py-2 bg-body-light">
                    <p class="font-w600 font-size-sm text-muted mb-0">
                        Tertunda
                    </p>
                </div>
            </div>
        </div>
        <div class="col-6 col-lg-4">
            <div class="block block-rounded block-link-shadow text-center">
                <div class="block-content block-content-full">
                    <div class="font-size-h2 text-primary">{{ $pesananProses }}</div>
                </div>
                <div class="block-content py-2 bg-body-light">
                    <p class="font-w600 font-size-sm text-muted mb-0">
                        Sedang Proses
                    </p>
                </div>
            </div>
        </div>
        <div class="col-6 col-lg-4">
            <div class="block block-rounded block-link-shadow text-center">
                <div class="block-content block-content-full">
                    <div class="font-size-h2 text-primary">{{ $pesananBerhasil }}</div>
                </div>
                <div class="block-content py-2 bg-body-light">
                    <p class="font-w600 font-size-sm text-muted mb-0">
                        Selesai
                    </p>
                </div>
            </div>
        </div>
    </div>
    <!-- END Quick Overview -->

    <!-- All Orders -->
    <div class="block block-rounded">
        <div class="block-header block-header-default">
            <h3 class="block-title">Semua Pesanan</h3>
        </div>
        <div class="block-content">
            <!-- Search Form -->
            <div class="form-group">
                <div class="input-group">
                    <input type="text" class="form-control form-control-alt"
                        placeholder="Cari Pesanan.." wire:model="search">
                    <div class="input-group-append">
                        <span class="input-group-text bg-body border-0">
                            <i class="fa fa-search"></i>
                        </span>
                    </div>
                </div>
            </div>
            <!-- END Search Form -->

            <!-- All Orders Table -->
            <div class="table-responsive">
                <table class="table table-borderless table-striped table-vcenter">
                    <thead>
                        <tr>
                            <th class="text-center" style="width: 100px;">ID</th>
                            <th>Waktu Pemesanan</th>
                            <th>Status</th>
                            <th>Pelanggan</th>
                            <th>No Meja</th>
                            <th class="text-center">Products</th>
                            <th class="text-right">Qty</th>
                            <th class="text-center">Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($pesanan as $pesanann)
                            <tr>
                                <td class="text-center font-size-sm">
                                    <strong>{{ $pesanann->id }}</strong>
                                </td>
                                <td class="text-center font-size-sm">
                                    <strong>{{ $pesanann->created_at }}</strong>
                                </td>
                                <td>
                                    @if($pesanann->status_pesanan_id === 2)
                                        <span class="badge badge-success">
                                            {{ $pesanann->status_pesanan->status }}
                                        </span>
                                    @elseif ($pesanann->status_pesanan_id === 1)
                                        <span class="badge badge-info">
                                            {{ $pesanann->status_pesanan->status }}
                                        </span>
                                    @else
                                        <span class="badge badge-warning">
                                            {{ $pesanann->status_pesanan->status }}
                                        </span>
                                    @endif
                                </td>
                                <td class="font-size-sm">
                                    {{-- Arahkan ke route transaksi berdasarkan id pesanan --}}
                                    <a class="font-w600" href="#">
                                        {{ $pesanann->pesanan->nama }}
                                    </a>
                                </td>
                                <td>
                                    <strong>
                                        {{ $pesanann->pesanan->no_meja }}
                                    </strong>
                                </td>
                                <td class="text-center font-size-sm">
                                    {{-- Arahkan ke route product --}}
                                    <a class="font-w600" href="#">
                                        {{ $pesanann->katalog->nama }}
                                    </a>
                                </td>
                                <td class="text-right font-size-sm">
                                    <strong>
                                        {{ $pesanann->qty }}
                                    </strong>
                                </td>
                                <td class="text-center">
                                    @if($pesanann->status_pesanan_id === 1)
                                        <button class="btn btn-sm btn-alt-secondary"
                                            data-toggle="tooltip" title="Proses"
                                            wire:click="setPesananProses({{ $pesanann->id }})"
                                        >
                                            <i class="fa fa-hourglass-half"></i>
                                        </button>
                                        <button class="btn btn-sm btn-alt-info" 
                                            data-toggle="tooltip" title="Selesai"
                                            wire:click="setPesananBerhasil({{ $pesanann->id }})"
                                        >
                                            <i class="fa fa-check-square"></i>
                                        </button>
                                    @elseif($pesanann->status_pesanan_id === 2)
                                        <button class="btn btn-sm btn-alt-info" 
                                            data-toggle="tooltip" title="Selesai"
                                            wire:click="setPesananBerhasil({{ $pesanann->id }})"
                                        >
                                            <i class="fa fa-check-square"></i>
                                        </button>
                                    @elseif($pesanann->status_pesanan_id === 3)
                                        <span class="badge badge-secondary">
                                            <i>Tidak ada aksi</i>
                                        </span>
                                    @endif
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="7" class="text-center">
                                    <i>Tidak ada pesanan</i>
                                </td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
                {{ $pesanan->links() }}
            </div>
            <!-- END All Orders Table -->
        </div>
    </div>
    <!-- END All Orders -->
</div>