routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\Customer\PesananController;
use App\Http\Controllers\Pengelola\PesananController as PengelolaPesananController;
use App\Http\Controllers\Pengelola\KatalogController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('guest.main');
})->name('guest.main');

require __DIR__ . '/auth.php';

// Route customer
Route::middleware(['auth', 'customer'])
    ->name('customer.')
    ->group(function () {
        Route::get('/pesanan', [PesananController::class, 'viewPesanan'])
            ->name('pesanan');
    });

// Route non customer (pengelola)
Route::middleware(['auth', 'pengelola'])
    ->name('pengelola.')
    ->prefix('pengelola')
    ->group(function () {
        Route::get('/dashboard', function () {
            $active = 'dashboard';
            return view('pengelola.dashboard', [
                'active' => $active,
            ]);
        })->name('dashboard');

        Route::get('pesanan', [PengelolaPesananController::class, 'index'])
            ->name('pesanan');

        Route::resource('katalog', KatalogController::class);
    });

app/Models/Katalog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Katalog extends Model
{
    use HasFactory;

    protected $table = 'katalog';
    protected $fillable = ['nama', 'harga', 'stok', 'gambar', 'deskripsi', 'kategori_katalog_id'];

    public $jumlahHarga = 0;

    public function pesanan()
    {
        return $this->belongsToMany(Pesanan::class)
            ->using(KatalogPesanan::class)
            ->withPivot('status_pesanan_id', 'qty')
            ->withTimestamps();
    }

    public function jumlah_harga()
    {
        $this->jumlahHarga = $this->pivot->qty * $this->harga;
        return $this->jumlahHarga;
    }
}

app/Http/Controllers/Pengelola/KatalogController.php
<?php

namespace App\Http\Controllers\Pengelola;

use App\Http\Controllers\Controller;
use App\Models\Katalog;
use App\Models\Kategori;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

use Exception;

class KatalogController extends Controller
{
    public $active;

    public function __construct()
    {
        $this->active = 'products';
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $katalog = Katalog::all();
        $stokHabis = Katalog::where('stok', 0)->count();

        return view('pengelola.katalog.index', [
            'katalog' => $katalog,
            'active' => $this->active,
            'stokHabis' => $stokHabis,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $kategori = Kategori::all();
        return view('pengelola.katalog.add', [
            'active' => $this->active,
            'kategori' => $kategori
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama' => 'required',
            'kategori' => 'required|exists:App\Models\Kategori,id',
            'harga' => 'required|numeric',
            'stok' => 'required|numeric',
            'deskripsi' => 'nullable',
            'gambar' => 'required|file|mimes:jpg,bmp,png'
        ], [
            'nama.required' => 'Nama tidak boleh kosong',
            'kategori.required' => 'Kategori tidak boleh kosong',
            'kategori.exists' => 'Kategori harus sesuai dengan data yang ada pada database',
            'harga.required' => 'Harga tidak boleh kosong',
            'harga.numeric' => 'Harga tidak boleh mengandung selain penomoran',
            'stok.required' => 'Stok tidak boleh kosong',
            'stok.numeric' => 'Stok tidak boleh mengandung selain penomoran',
            'gambar.required' => 'Gambar tidak boleh kosong',
            'gambar.file' => 'Gambar harus berbentuk file',
            'gambar.mimes' => 'Format gambar harus :values'
        ]);

        try {
            $produk = $request->gambar->store('public/produk');
            $namaProduk = explode('/', $produk)[2];
            $insert = Katalog::create([
                'nama' => $request->nama,
                'kategori_katalog_id' => $request->kategori,
                'harga' => $request->harga,
                'stok' => $request->stok,
                'deskripsi' => $request->deskripsi,
                'gambar' => $namaProduk
            ]);
            return redirect()
                ->route('pengelola.katalog.index')
                ->with('success', 'Berhasil menambahkan data');
        } catch (Exception $e) {
            Storage::delete('public/produk/' . $namaProduk);
            return redirect()->back()->with('error', $e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Katalog $katalog)
    {
        $kategori = Kategori::all();
        return view('pengelola.katalog.edit', [
            'katalog' => $katalog,
            'active' => $this->active,
            'kategori' => $kategori,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Katalog $katalog)
    {
        Storage::delete('public/produk/' . $katalog->gambar);
        $katalog->delete();

        return redirect()->back()->with('success', 'Berhasil hapus produk');
    }
}

app/Http/Controllers/Pengelola/PesananController.php
<?php

namespace App\Http\Controllers\Pengelola;

use App\Http\Controllers\Controller;

class PesananController extends Controller
{
    public function index()
    {
        $active = 'orders';

        return view('pengelola.orders', [
            'active' => $active,
        ]);
    }
}

resources/views/pengelola/katalog/add.blade.php
@extends('base')

@section('judul', 'Tambah Katalog | Jenggala Kops')

@section('sidebar')
    @include('pengelola._partials.sidebar')
@endsection

@section('header')
    @include('pengelola._partials.header')
@endsection

@section('content')
    <!-- Info -->
    <div class="block block-rounded">
        <div class="block-header block-header-default">
            <h3 class="block-title">Tambah Data</h3>
        </div>
        <div class="block-content">

            @if(session('error'))
                <div class="alert alert-danger">
                    {{ session('error') }}
                </div>
            @endif

            <div class="row justify-content-center">
                <div class="col-md-10 col-lg-8">
                    <form action="{{ route('pengelola.katalog.store') }}" 
                        enctype="multipart/form-data"
                        method="POST">
                        @csrf
                        <div class="form-group">
                            <label for="one-ecom-product-name">Nama</label>
                            <input type="text" class="form-control" id="one-ecom-product-name" name="nama" value="{{ old('nama') }}">
                            @error('nama')
                                <small class="text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="one-ecom-product-category">Kategori</label>
                            <select class="js-select2 form-control" id="one-ecom-product-category" name="kategori" style="width: 100%;" data-placeholder="Choose one..">
                                <option></option>
                                @foreach ($kategori as $_kategori)
                                    <option value="{{ $_kategori->id }}"
                                        {{ old('kategori') == $_kategori->id ? 'selected' : '' }}    
                                    >
                                        {{ $_kategori->nama }}
                                    </option>
                                @endforeach
                            </select>
                            @error('kategori')
                                <small class="text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                        <div class="form-group row">
                            <div class="col-md-6">
                                <label for="one-ecom-product-price">Harga</label>
                                <input type="text" class="form-control" id="one-ecom-product-price" name="harga"
                                value="{{ old('harga') }}">
                                @error('harga')
                                    <small class="text-danger">{{ $message }}</small>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-6">
                                <label for="one-ecom-product-stock">Stok</label>
                                <input type="text" class="form-control" id="one-ecom-product-stock" name="stok"
                                value="{{ old('stok') }}">
                                @error('stok')
                                    <small class="text-danger">{{ $message }}</small>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="one-ecom-product-description-short">Deskripsi</label>
                            <textarea class="form-control" id="one-ecom-product-description-short" name="deskripsi" rows="4"></textarea>
                        </div>
                        <div class="form-group">
                            <label class="d-block" for="example-file-input">Gambar</label>
                            <input type="file" id="example-file-input" name="gambar">
                            @error('gambar')
                                <small class="text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-alt-success">Simpan</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- END Info -->
@endsection

@section('js_after')
    <script src="{{ asset('assets/oneui/js/plugins/chart.js/Chart.bundle.min.js') }}"></script>
    <script src="{{ asset('assets/oneui/js/pages/be_pages_ecom_dashboard.min.js') }}"></script>
@endsection

resources/views/pengelola/katalog/edit.blade.php
@extends('base')

@section('judul', 'Edit Katalog | Jenggala Kops')

@section('sidebar')
    @include('pengelola._partials.sidebar')
@endsection

@section('header')
    @include('pengelola._partials.header')
@endsection

@section('content')
    <div class="row">
        <div class="col-12 col-lg-12">
            <a class="block block-rounded block-link-shadow text-center" href="#">
                <div class="block-content block-content-full">
                    <div class="font-size-h2 text-dark">{{ $katalog->stok }}</div>
                </div>
                <div class="block-content py-2 bg-body-light">
                    <p class="font-w600 font-size-sm text-info mb-0">
                        Tersedia
                    </p>
                </div>
            </a>
        </div>
        <div class="col-lg-12 col-12">
            <a class="block block-rounded block-link-shadow text-center" href="#">
                <div class="block-content block-content-full">
                    <img src="{{ 
                                !$katalog->gambar ? 
                                asset('assets/img/default_katalog.png') : 
                                asset('storage/produk/' . $katalog->gambar)
                        }}" 
                    >
                </div>
                <div class="block-content py-2 bg-body-light">
                    <p class="font-w600 font-size-sm text-muted mb-0">
                        Gambar
                    </p>
                </div>
            </a>
        </div>
    </div>

    <!-- Info -->
    <div class="block block-rounded">
        <div class="block-header block-header-default">
            <h3 class="block-title">Edit Data</h3>
        </div>
        <div class="block-content">

            @if(session('error'))
                <div class="alert alert-danger">
                    {{ session('error') }}
                </div>
            @endif

            <div class="row justify-content-center">
                <div class="col-md-10 col-lg-8">
                    <form action="{{ route('pengelola.katalog.store') }}" 
                        enctype="multipart/form-data"
                        method="POST">
                        @csrf
                        <div class="form-group">
                            <label for="one-ecom-product-name">Nama</label>
                            <input type="text" class="form-control" id="one-ecom-product-name" name="nama" value="{{ old('nama', $katalog->nama) }}">
                            @error('nama')
                                <small class="text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="one-ecom-product-category">Kategori</label>
                            <select class="js-select2 form-control" id="one-ecom-product-category" name="kategori" style="width: 100%;" data-placeholder="Choose one..">
                                <option></option>
                                @foreach ($kategori as $_kategori)
                                    <option value="{{ $_kategori->id }}"
                                        {{ old('kategori', $katalog->kategori_katalog_id) == $_kategori->id ? 'selected' : '' }}    
                                    >
                                        {{ $_kategori->nama }}
                                    </option>
                                @endforeach
                            </select>
                            @error('kategori')
                                <small class="text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                        <div class="form-group row">
                            <div class="col-md-6">
                                <label for="one-ecom-product-price">Harga</label>
                                <input type="text" class="form-control" id="one-ecom-product-price" name="harga"
                                value="{{ old('harga', $katalog->harga) }}">
                                @error('harga')
                                    <small class="text-danger">{{ $message }}</small>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-6">
                                <label for="one-ecom-product-stock">Stok</label>
                                <input type="text" class="form-control" id="one-ecom-product-stock" name="stok"
                                value="{{ old('stok', $katalog->stok) }}">
                                @error('stok')
                                    <small class="text-danger">{{ $message }}</small>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="one-ecom-product-description-short">Deskripsi</label>
                            <textarea class="form-control" id="one-ecom-product-description-short" name="deskripsi" rows="4"></textarea>
                        </div>
                        <div class="form-group">
                            <label class="d-block" for="example-file-input">Gambar</label>
                            <input type="file" id="example-file-input" name="gambar">
                            @error('gambar')
                                <small class="text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-alt-success">Simpan</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- END Info -->
@endsection

@section('js_after')
    <script src="{{ asset('assets/oneui/js/plugins/chart.js/Chart.bundle.min.js') }}"></script>
    <script src="{{ asset('assets/oneui/js/pages/be_pages_ecom_dashboard.min.js') }}"></script>
@endsection

resources/views/pengelola/katalog/index.blade.php
@extends('base')

@section('judul', 'Katalog | Jenggala Kops')

@section('sidebar')
    @include('pengelola._partials.sidebar')
@endsection

@section('header')
    @include('pengelola._partials.header')
@endsection

@section('content')
     <!-- Quick Overview -->
    <div class="row">
        <div class="col-6 col-lg-4">
            <a class="block block-rounded block-link-shadow text-center" 
            href="{{ route('pengelola.katalog.create') }}">
                <div class="block-content block-content-full">
                    <div class="font-size-h2 text-success">
                        <i class="fa fa-plus"></i>
                    </div>
                </div>
                <div class="block-content py-2 bg-body-light">
                    <p class="font-w600 font-size-sm text-success mb-0">
                        Tambah Produk Baru
                    </p>
                </div>
            </a>
        </div>
        <div class="col-6 col-lg-4">
            <a class="block block-rounded block-link-shadow text-center" href="javascript:void(0)">
                <div class="block-content block-content-full">
                    <div class="font-size-h2 text-danger">{{ $stokHabis }}</div>
                </div>
                <div class="block-content py-2 bg-body-light">
                    <p class="font-w600 font-size-sm text-danger mb-0">
                        Habis
                    </p>
                </div>
            </a>
        </div>
        <div class="col-6 col-lg-4">
            <a class="block block-rounded block-link-shadow text-center" href="#">
                <div class="block-content block-content-full">
                    <div class="font-size-h2 text-dark">{{ count($katalog) }}</div>
                </div>
                <div class="block-content py-2 bg-body-light">
                    <p class="font-w600 font-size-sm text-muted mb-0">
                        Semua Produk
                    </p>
                </div>
            </a>
        </div>
    </div>
    <!-- END Quick Overview -->

    <!-- All Products -->
    <div class="block block-rounded">
        <div class="block-header block-header-default">
            <h3 class="block-title">Semua Produk</h3>
            <div class="block-options">
                <div class="dropdown">
                    <button type="button" class="btn-block-option" id="dropdown-ecom-filters" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Filters <i class="fa fa-angle-down ml-1"></i>
                    </button>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdown-ecom-filters">
                        <a class="dropdown-item d-flex align-items-center justify-content-between" href="javascript:void(0)">
                            New
                            <span class="badge badge-success badge-pill">260</span>
                        </a>
                        <a class="dropdown-item d-flex align-items-center justify-content-between" href="javascript:void(0)">
                            Out of Stock
                            <span class="badge badge-danger badge-pill">24</span>
                        </a>
                        <a class="dropdown-item d-flex align-items-center justify-content-between" href="javascript:void(0)">
                            All
                            <span class="badge badge-primary badge-pill">14503</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="block-content">
            @if(session('success'))
                <div class="alert alert-success">
                    {{ session('success') }}
                </div>
            @endif
            <!-- Search Form -->
            <form action="be_pages_ecom_products.html" method="POST" onsubmit="return false;">
                <div class="form-group">
                    <div class="input-group">
                        <input type="text" class="form-control form-control-alt" id="one-ecom-products-search" name="one-ecom-products-search" placeholder="Search all products..">
                        <div class="input-group-append">
                            <span class="input-group-text bg-body border-0">
                                <i class="fa fa-search"></i>
                            </span>
                        </div>
                    </div>
                </div>
            </form>
            <!-- END Search Form -->

            <!-- All Products Table -->
            <div class="table-responsive">
                <table class="table table-borderless table-striped table-vcenter">
                    <thead>
                        <tr>
                            <th class="text-center" style="width: 100px;">ID</th>
                            <th class="d-none d-md-table-cell">Product</th>
                            <th>Status</th>
                            <th class="d-none d-sm-table-cell text-right">Harga</th>
                            <th class="text-center">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($katalog as $_katalog)
                            <tr>
                                <td class="text-center font-size-sm">
                                    <a class="font-w600" href="be_pages_ecom_product_edit.html">
                                        <strong>{{ $_katalog->id }}</strong>
                                    </a>
                                </td>
                                <td class="d-none d-md-table-cell font-size-sm">
                                    <a href="#">
                                        {{ $_katalog->nama }}
                                    </a>
                                </td>
                                <td>
                                    @if($_katalog->stok != 0)
                                        <span class="badge badge-info">
                                            Tersedia
                                        </span>
                                    @else
                                        <span class="badge badge-danger">
                                            Habis
                                        </span>
                                    @endif
                                </td>
                                <td class="text-right d-none d-sm-table-cell font-size-sm">
                                    <strong>RP.{{ $_katalog->harga }}</strong>
                                </td>
                                <td class="text-center font-size-sm">
                                    <a class="btn btn-sm btn-alt-info" 
                                    href="{{ route('pengelola.katalog.edit', [
                                        'katalog' => $_katalog->id
                                    ]) }}" 
                                    data-toggle="tooltip" title="Edit">
                                        <i class="far fa-edit"></i>
                                    </a>
                                    <form action="{{ route('pengelola.katalog.destroy', [
                                        'katalog' => $_katalog->id
                                    ]) }}"
                                        method="POST"
                                        style="display: inline"
                                    >
                                        @csrf
                                        @method('DELETE')
                                        <button class="btn btn-sm btn-alt-danger"
                                            type="submit"
                                            data-toggle="tooltip" title="Delete">
                                            <i class="fa fa-times-circle"></i>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            <!-- END All Products Table -->

            <!-- Pagination -->
            {{-- <nav aria-label="Photos Search Navigation">
                <ul class="pagination pagination-sm justify-content-end mt-2">
                    <li class="page-item">
                        <a class="page-link" href="javascript:void(0)" tabindex="-1" aria-label="Previous">
                            Prev
                        </a>
                    </li>
                    <li class="page-item active">
                        <a class="page-link" href="javascript:void(0)">1</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="javascript:void(0)">2</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="javascript:void(0)">3</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="javascript:void(0)">4</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="javascript:void(0)" aria-label="Next">
                            Next
                        </a>
                    </li>
                </ul>
            </nav> --}}
            <!-- END Pagination -->
        </div>
    </div>
    <!-- END All Products -->
@endsection

@section('js_after')
    <script src="{{ asset('assets/oneui/js/plugins/chart.js/Chart.bundle.min.js') }}"></script>
    <script src="{{ asset('assets/oneui/js/pages/be_pages_ecom_dashboard.min.js') }}"></script>
@endsection